# Change these first
owner: Paper319 # Your GitHub organization or username, where this repository lives
repo: Monitor # The name of this repository

sites:
  - name: PaperFin
    url: $MEDIA_URL/health
  - name: Account Login
    url: $ACCOUNT_URL
  - name: Downloader
    url: $DOWNLOAD_URL
  - name: Movie Manager
    url: $MOVIE_URL
  - name: Shows Manager
    url: $SHOWS_URL
  - name: Request
    url: $REQUEST_URL
  - name: Lookup Stuff
    url: $SEARCH_URL
  - name: Subtitles
    url: $SUBTITLES_URL
  - name: Enocder
    url: $ENCODER_URL
  - name: Cloud Files
    url: $CLOUD_URL
    expectedStatusCodes:
      - 403
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: domain.com
  baseUrl: /Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**HELLO?** Is it you or is it broke?"
  introMessage: Then I already know about it.
  navbar:
    - title: Status
      href: /Monitor


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
